// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "ecommerce/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockProductRepository is an autogenerated mock type for the ProductRepository type
type MockProductRepository struct {
	mock.Mock
}

type MockProductRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductRepository) EXPECT() *MockProductRepository_Expecter {
	return &MockProductRepository_Expecter{mock: &_m.Mock}
}

// CreateProduct provides a mock function with given fields: _a0, _a1
func (_m *MockProductRepository) CreateProduct(_a0 context.Context, _a1 domain.Product) (domain.Product, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 domain.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Product) (domain.Product, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Product) domain.Product); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(domain.Product)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Product) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_CreateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProduct'
type MockProductRepository_CreateProduct_Call struct {
	*mock.Call
}

// CreateProduct is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 domain.Product
func (_e *MockProductRepository_Expecter) CreateProduct(_a0 interface{}, _a1 interface{}) *MockProductRepository_CreateProduct_Call {
	return &MockProductRepository_CreateProduct_Call{Call: _e.mock.On("CreateProduct", _a0, _a1)}
}

func (_c *MockProductRepository_CreateProduct_Call) Run(run func(_a0 context.Context, _a1 domain.Product)) *MockProductRepository_CreateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Product))
	})
	return _c
}

func (_c *MockProductRepository_CreateProduct_Call) Return(_a0 domain.Product, _a1 error) *MockProductRepository_CreateProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_CreateProduct_Call) RunAndReturn(run func(context.Context, domain.Product) (domain.Product, error)) *MockProductRepository_CreateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProduct provides a mock function with given fields: _a0, _a1
func (_m *MockProductRepository) DeleteProduct(_a0 context.Context, _a1 int) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductRepository_DeleteProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProduct'
type MockProductRepository_DeleteProduct_Call struct {
	*mock.Call
}

// DeleteProduct is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 int
func (_e *MockProductRepository_Expecter) DeleteProduct(_a0 interface{}, _a1 interface{}) *MockProductRepository_DeleteProduct_Call {
	return &MockProductRepository_DeleteProduct_Call{Call: _e.mock.On("DeleteProduct", _a0, _a1)}
}

func (_c *MockProductRepository_DeleteProduct_Call) Run(run func(_a0 context.Context, _a1 int)) *MockProductRepository_DeleteProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockProductRepository_DeleteProduct_Call) Return(_a0 error) *MockProductRepository_DeleteProduct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductRepository_DeleteProduct_Call) RunAndReturn(run func(context.Context, int) error) *MockProductRepository_DeleteProduct_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllProducts provides a mock function with given fields: _a0
func (_m *MockProductRepository) GetAllProducts(_a0 context.Context) ([]domain.Product, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetAllProducts")
	}

	var r0 []domain.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Product, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Product); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_GetAllProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllProducts'
type MockProductRepository_GetAllProducts_Call struct {
	*mock.Call
}

// GetAllProducts is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockProductRepository_Expecter) GetAllProducts(_a0 interface{}) *MockProductRepository_GetAllProducts_Call {
	return &MockProductRepository_GetAllProducts_Call{Call: _e.mock.On("GetAllProducts", _a0)}
}

func (_c *MockProductRepository_GetAllProducts_Call) Run(run func(_a0 context.Context)) *MockProductRepository_GetAllProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockProductRepository_GetAllProducts_Call) Return(_a0 []domain.Product, _a1 error) *MockProductRepository_GetAllProducts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_GetAllProducts_Call) RunAndReturn(run func(context.Context) ([]domain.Product, error)) *MockProductRepository_GetAllProducts_Call {
	_c.Call.Return(run)
	return _c
}

// GetProductByID provides a mock function with given fields: _a0, _a1
func (_m *MockProductRepository) GetProductByID(_a0 context.Context, _a1 int) (domain.Product, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetProductByID")
	}

	var r0 domain.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (domain.Product, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) domain.Product); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(domain.Product)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_GetProductByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductByID'
type MockProductRepository_GetProductByID_Call struct {
	*mock.Call
}

// GetProductByID is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 int
func (_e *MockProductRepository_Expecter) GetProductByID(_a0 interface{}, _a1 interface{}) *MockProductRepository_GetProductByID_Call {
	return &MockProductRepository_GetProductByID_Call{Call: _e.mock.On("GetProductByID", _a0, _a1)}
}

func (_c *MockProductRepository_GetProductByID_Call) Run(run func(_a0 context.Context, _a1 int)) *MockProductRepository_GetProductByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockProductRepository_GetProductByID_Call) Return(_a0 domain.Product, _a1 error) *MockProductRepository_GetProductByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_GetProductByID_Call) RunAndReturn(run func(context.Context, int) (domain.Product, error)) *MockProductRepository_GetProductByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProduct provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockProductRepository) UpdateProduct(_a0 context.Context, _a1 int, _a2 domain.Product) (domain.Product, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProduct")
	}

	var r0 domain.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, domain.Product) (domain.Product, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, domain.Product) domain.Product); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(domain.Product)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, domain.Product) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_UpdateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProduct'
type MockProductRepository_UpdateProduct_Call struct {
	*mock.Call
}

// UpdateProduct is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 int
//   - _a2 domain.Product
func (_e *MockProductRepository_Expecter) UpdateProduct(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockProductRepository_UpdateProduct_Call {
	return &MockProductRepository_UpdateProduct_Call{Call: _e.mock.On("UpdateProduct", _a0, _a1, _a2)}
}

func (_c *MockProductRepository_UpdateProduct_Call) Run(run func(_a0 context.Context, _a1 int, _a2 domain.Product)) *MockProductRepository_UpdateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(domain.Product))
	})
	return _c
}

func (_c *MockProductRepository_UpdateProduct_Call) Return(_a0 domain.Product, _a1 error) *MockProductRepository_UpdateProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_UpdateProduct_Call) RunAndReturn(run func(context.Context, int, domain.Product) (domain.Product, error)) *MockProductRepository_UpdateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProductRepository creates a new instance of MockProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductRepository {
	mock := &MockProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
